BEGIN;

-- =========================================
-- 1. Bảng MERCHANT (cửa hàng / nhà hàng)
-- =========================================
CREATE TABLE public.merchant (
  merchant_id uuid NOT NULL DEFAULT gen_random_uuid(),
  merchant_name text NOT NULL,
  address text,
  phone text,
  email text,
  status boolean DEFAULT true,
  user_id uuid, -- FK tới auth.users (account của chủ quán)
  created_at timestamptz DEFAULT now(),
  CONSTRAINT merchant_pkey PRIMARY KEY (merchant_id),
  CONSTRAINT merchant_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

-- =========================================
-- 2. Bảng CUSTOMER (khách hàng)
-- =========================================
CREATE TABLE public.customer (
  customer_id uuid NOT NULL, -- chính là auth.users.id
  customer_name text NOT NULL,
  phone text,
  address text,
  email text,
  status boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT customer_pkey PRIMARY KEY (customer_id),
  CONSTRAINT customer_customer_id_fkey
    FOREIGN KEY (customer_id) REFERENCES auth.users(id)
);

-- =========================================
-- 3. Bảng CATEGORY (danh mục món của từng merchant)
-- =========================================
CREATE TABLE public.category (
  category_id integer GENERATED BY DEFAULT AS IDENTITY,
  name text NOT NULL,
  status boolean DEFAULT true,
  created_at timestamptz DEFAULT now(),
  merchant_id uuid,
  CONSTRAINT category_pkey PRIMARY KEY (category_id),
  CONSTRAINT category_merchant_id_fkey
    FOREIGN KEY (merchant_id) REFERENCES public.merchant(merchant_id)
);

-- =========================================
-- 4. Bảng PRODUCT (món ăn / đồ uống)
-- =========================================
CREATE TABLE public.product (
  product_id integer GENERATED BY DEFAULT AS IDENTITY,
  product_name text NOT NULL,
  category_id integer,
  price numeric NOT NULL DEFAULT 0.00,
  image text,
  description text,
  rating numeric,
  status boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  merchant_id uuid,
  CONSTRAINT product_pkey PRIMARY KEY (product_id),
  CONSTRAINT product_category_id_fkey
    FOREIGN KEY (category_id) REFERENCES public.category(category_id),
  CONSTRAINT product_merchant_id_fkey
    FOREIGN KEY (merchant_id) REFERENCES public.merchant(merchant_id)
);

-- =========================================
-- 5. Bảng ORDERS (đơn hàng)
-- =========================================
CREATE TABLE public.orders (
  order_id integer GENERATED BY DEFAULT AS IDENTITY,
  customer_id uuid,
  order_date timestamptz DEFAULT now(),
  delivery_address text,
  total_amount numeric NOT NULL DEFAULT 0.00,
  order_status text DEFAULT 'pending', -- pending / completed / cancelled...
  payment_status text DEFAULT 'unpaid', -- unpaid / paid / failed...
  note text,
  merchant_id uuid,
  CONSTRAINT orders_pkey PRIMARY KEY (order_id),
  CONSTRAINT orders_customer_id_fkey
    FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id),
  CONSTRAINT orders_merchant_id_fkey
    FOREIGN KEY (merchant_id) REFERENCES public.merchant(merchant_id)
);

-- =========================================
-- 6. Bảng ORDER_DETAIL (chi tiết từng món trong đơn)
-- =========================================
CREATE TABLE public.order_detail (
  order_detail_id integer GENERATED BY DEFAULT AS IDENTITY,
  order_id integer,
  product_id integer,
  quantity integer NOT NULL DEFAULT 1,
  price numeric NOT NULL,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT order_detail_pkey PRIMARY KEY (order_detail_id),
  CONSTRAINT order_detail_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES public.orders(order_id),
  CONSTRAINT order_detail_product_id_fkey
    FOREIGN KEY (product_id) REFERENCES public.product(product_id)
);

-- =========================================
-- 7. Bảng PAYMENT (thanh toán)
-- =========================================
CREATE TABLE public.payment (
  payment_id integer GENERATED BY DEFAULT AS IDENTITY,
  order_id integer,
  payment_date timestamptz DEFAULT now(),
  amount numeric NOT NULL,
  method text,          -- momo / cash / card...
  transaction_id text,  -- mã giao dịch từ gateway
  note text,
  CONSTRAINT payment_pkey PRIMARY KEY (payment_id),
  CONSTRAINT payment_order_id_fkey
    FOREIGN KEY (order_id) REFERENCES public.orders(order_id)
);

-- =========================================
-- 8. Bảng CART (giỏ hàng tạm của customer)
-- =========================================
CREATE TABLE public.cart (
  cart_id integer GENERATED BY DEFAULT AS IDENTITY,
  customer_id uuid,
  product_id integer,
  quantity integer NOT NULL DEFAULT 1,
  price numeric NOT NULL,
  added_at timestamptz DEFAULT now(),
  status text DEFAULT 'active', -- active / checked_out / abandoned...
  merchant_id uuid,
  CONSTRAINT cart_pkey PRIMARY KEY (cart_id),
  CONSTRAINT cart_customer_id_fkey
    FOREIGN KEY (customer_id) REFERENCES public.customer(customer_id),
  CONSTRAINT cart_product_id_fkey
    FOREIGN KEY (product_id) REFERENCES public.product(product_id),
  CONSTRAINT cart_merchant_id_fkey
    FOREIGN KEY (merchant_id) REFERENCES public.merchant(merchant_id)
);

COMMIT;
